### ISSUE TITLE
Questions and Comments

### ISSUE THREAD

**Issue by Cool-Gamer** [AeroWidescreen/NFS-SH-WidescreenFixWiki#1]
Hi Aero,

Thanks a lot for NeedForSpeed Underground and Silent Hill widescreen patches.  I have a couple of questions that I want to ask.

Will you eventually add the High Resolution Reflections enhancement that you posted on Youtube to your NFS Underground widescreen patch?  Or is that something that can not be done via ASI loader?

Is it possible to add Xbox Controller support (Xinput support) to old games (such as silent hill series) via ASI patches? Or again, is that something that can't be done via ASI loader? 

Is it possible to take advantage of Nvidia Gameworks DLLs and add features such as HBAO+, TXAA, Global Illumination, advanced shadows, DoF Bokeh, etc. via ASI loader patches?  I wrote some links below, the last one includes implementation example for HBAO+.
https://developer.nvidia.com/gameworks-visualfx-overview
https://developer.nvidia.com/postworks
http://docs.nvidia.com/gameworks/content/gameworkslibrary/visualfx/hbao/product.html

Nvidia provides example source code (free of charge) that shows programmers how to use HBAO+ and other Gameworks features in their games. It is on Github but you have to signup through Nvidia's website to request access to the HBAO+ repository (it is hidden from public view). Instructions are shown on the link below. 
https://developer.nvidia.com/gameworks-source-github

After you complete the signup you should be able to access the "hidden HBAO+ repo" under the following web page when you login to Github.
https://github.com/NVIDIAGameWorks

I am asking these questions because it might be possible to make NFS and Silent Hill games look amazing, if you can find a way to integrate Nvidia Game Works DLL calls into your widescreen ASI scripts.  Those DLLs work on all platforms (Intel GPUs, AMD GPUs and Nvidia GPUs), not just on Nvidia. 

Thanks for your replies in advance.  Thanks again for NFS and Silent Hill patches.

**Comment by AeroWidescreen** [comment]
> Will you eventually add the High Resolution Reflections enhancement that you posted on Youtube to your NFS Underground widescreen patch? Or is that something that can not be done via ASI loader?

None of the widescreen fixes are mine, except for arguably SH2 and SH3. Anyway, to answer your question it _can_ be done through an ASI script, but I have to ask ThirteenAG about it since I don't know C++ to do it myself. Or you could ask him yourself [here](https://github.com/ThirteenAG/WidescreenFixesPack/issues).

> Is it possible to add Xbox Controller support (Xinput support) to old games (such as silent hill series) via ASI patches? Or again, is that something that can't be done via ASI loader?

You can use your Xbox controller with all buttons and rumble support using [XInput Plus](https://sites.google.com/site/0dd14lab/xinput-plus) for SH2 and SH3. I don't know about SH4. If you're talking about a console experience with button prompts, then I don't think so.

The NFS games already worked with Xinput controllers for the most part, so all we did was remap some of the buttons that were wrong and replaced the textures. In Silent Hill everything can be remapped in the options menu when using Xinput Plus, and there's no button textures we can replace.

> Is it possible to take advantage of Nvidia Gameworks DLLs and add features such as HBAO+, TXAA, Global Illumination, advanced shadows, DoF Bokeh, etc. via ASI loader patches? I wrote some links below, the last one includes implementation example for HBAO+.

I have absolutely no idea, sorry. Try asking [elishacloud](https://github.com/elishacloud/Silent-Hill-2-Enhancements).

**Comment by Cool-Gamer** [comment]
Thanks for your replies Aero.  I submitted a feature request to elishacloud on Github about Gameworks DLL integration.

Thanks for telling me about XInput Plus.  I did not know about it.  I will test it with SH2, SH3 and other old games.

Regarding NFSU High Resolution Reflections, it might be better if you ask ThirteenAG about it since you already have rapport with him.   You also know the technical details of the enhancement.  Please don't misunderstand, I am not trying to pressure you into doing the High Resolution Reflections Enhancement.  It is just that, it has a higher probability of getting implemented if you ask ThirteenAG about it and work together on it.  The game will really look good if that enhancement gets implemented.

Thanks again for all your contributions to SH and NFSU Widescreen fixes.

**Comment by AeroWidescreen** [comment]
> Thanks for telling me about XInput Plus. I did not know about it. I will test it with SH2, SH3 and other old games.

There's a really good guide for Silent Hill 2 that shows you how to install it with the widescreen fix: http://widescreenfix.townofsilenthill.com/SH2/ Just keep in mind that the rumble effect might not work even though it used to.

For Silent Hill 3 you simply rename the widescreen fix's dinput8.dll to dsound.dll, open XInput Plus, enable DirectInput Output and apply.

> Regarding NFSU High Resolution Reflections, it might be better if you ask ThirteenAG about it since you already have rapport with him. You also know the technical details of the enhancement. Please don't misunderstand, I am not trying to pressure you into doing the High Resolution Reflections Enhancement. It is just that, it has a higher probability of getting implemented if you ask ThirteenAG about it and work together on it. The game will really look good if that enhancement gets implemented.

I was going to ask him anyway, but I haven't yet because I'm still working on Carbon; that game is a mess when it comes to its road reflections, so I need to simplify that first.
